version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: doughjo-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: doughjo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - doughjo-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doughjo-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:password123@mongodb:27017/doughjo?authSource=admin
      FLASK_ENV: development
      FLASK_APP: app.py
    ports:
      - "5001:5000"   # host:container
    networks:
      - doughjo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: doughjo-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - doughjo-network

volumes:
  mongodb_data:

networks:
  doughjo-network:
    driver: bridge
